# Copyright © 2026 Tomer Preis. All rights reserved. Unauthorized copying or distribution is prohibited.
"""Constants used by the bridge settings package."""

SETTINGS_ENV_PREFIX = "BRIDGE_"
SETTINGS_ENV_FILE = ".env"
SETTINGS_ENV_FILE_ENCODING = "utf-8"
SETTINGS_EXTRA_POLICY = "ignore"

DEFAULT_BACKEND_URL = "http://localhost:3001"
DEFAULT_DRIVER = "demo"
DEFAULT_SERIAL_PORT = "COM3"
DEFAULT_BAUD_RATE = 9600
DEFAULT_VISA_RESOURCE = "GPIB0::17::INSTR"
DEFAULT_MEAS_FREQ_HZ = 1_000.0
DEFAULT_POLL_INTERVAL_S = 1.0
DEFAULT_DEMO_FREQ_MIN_HZ = 100.0
DEFAULT_DEMO_FREQ_MAX_HZ = 10_000_000.0
DEFAULT_DEMO_CUVETTE_GAP_MM = 4.0
DEFAULT_DEMO_CUVETTE_AREA_CM2 = 0.5
DEFAULT_PB_HOST = "192.168.1.100"
DEFAULT_PB_TCP_PORT = 20000
DEFAULT_PB_TCP_TIMEOUT_S = 5.0
DEFAULT_LOG_LEVEL = "INFO"

ALLOWED_BACKEND_URL_SCHEMES = ("http://", "https://")